version: '3.9'
services:
  mic-database:
    image: mongo
    ports:
      - '27017:27017'
  mic-backend:
    build: backend/
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://host.docker.internal:27017/openmic
    ports:
      - '3001:3001'
    depends_on:
      - mic-database
  mic-frontend:
    build:
      context: /client
      args:
        VITE_BACKEND_URL: http://localhost:3001/api/v1
    ports:
      - '3000:80'
    depends_on:
      - mic-backend
